### ISSUE TITLE
Cannot install the application from the zip file in the Release section

### ISSUE THREAD

**Issue by LilShieru** [CallMeQan/Osu-skin-Manager#2]
When I run the setup file in the ZIP Compressed File from the Release section of this repository, I got this setup error:

![Error](https://i.postimg.cc/htB9hbSS/Screenshot-41.png)

And here's the log file:

```
PLATFORM VERSION INFO
	Windows 			: 10.0.22000.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4161.0 built by: NET48REL1
	clr.dll 			: 4.8.4161.0 built by: NET48REL1
	dfdll.dll 			: 4.8.4161.0 built by: NET48REL1
	dfshim.dll 			: 10.0.22000.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Downloads/osu.skin-manager-v0.1/Osu!skin%20Manager.application

IDENTITIES
	Deployment Identity		: Osu!skin Manager.application, Version=0.0.1.0, Culture=neutral, PublicKeyToken=99bcc0f8ed963e35, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Downloads\osu.skin-manager-v0.1\Osu!skin Manager.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/Downloads/osu.skin-manager-v0.1/Application Files/Osu!skin Manager_0_0_1_0/Osu!skin Manager.exe.manifest did not succeed.
		+ Could not find a part of the path 'C:\Downloads\osu.skin-manager-v0.1\Application Files\Osu!skin Manager_0_0_1_0\Osu!skin Manager.exe.manifest'.
		+ Could not find a part of the path 'C:\Downloads\osu.skin-manager-v0.1\Application Files\Osu!skin Manager_0_0_1_0\Osu!skin Manager.exe.manifest'.
		+ Could not find a part of the path 'C:\Downloads\osu.skin-manager-v0.1\Application Files\Osu!skin Manager_0_0_1_0\Osu!skin Manager.exe.manifest'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [27/7/2021 5:30:23 PM] : Activation of C:\Downloads\osu.skin-manager-v0.1\Osu!skin Manager.application has started.
	* [27/7/2021 5:30:24 PM] : Processing of deployment manifest has successfully completed.
	* [27/7/2021 5:30:24 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [27/7/2021 5:30:24 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/Downloads/osu.skin-manager-v0.1/Application Files/Osu!skin Manager_0_0_1_0/Osu!skin Manager.exe.manifest did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find a part of the path 'C:\Downloads\osu.skin-manager-v0.1\Application Files\Osu!skin Manager_0_0_1_0\Osu!skin Manager.exe.manifest'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find a part of the path 'C:\Downloads\osu.skin-manager-v0.1\Application Files\Osu!skin Manager_0_0_1_0\Osu!skin Manager.exe.manifest'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.DirectoryNotFoundException
		- Could not find a part of the path 'C:\Downloads\osu.skin-manager-v0.1\Application Files\Osu!skin Manager_0_0_1_0\Osu!skin Manager.exe.manifest'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

Can you fix it?

**Comment by CallMeQan** [comment]
Oops, sorry about that, i just replaced the release file to .exe, now you dont have to go through the setup section. You can download it again [here](https://github.com/CallMeQan/Osu-skin-Manager/releases/tag/v0.1)
